# Generated by Django 4.0.2 on 2022-04-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_eventmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('venue', models.CharField(max_length=100)),
                ('venueaddress', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('entryfee', models.BigIntegerField()),
            ],
            options={
                'db_table': 'addevent',
            },
        ),
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'administration',
            },
        ),
    ]
