# Generated by Django 4.0.2 on 2022-04-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_addevent_administration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addevent',
            name='description',
            field=models.TextField(),
        ),
    ]
