# Generated by Django 4.0.2 on 2022-04-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_remove_addevent_contact_addevent_contactnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addevent',
            name='contactnumber',
            field=models.BigIntegerField(),
        ),
    ]
