# Generated by Django 4.0.2 on 2022-04-28 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0006_alter_addevent_contactnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.BigIntegerField()),
                ('Datetime', models.DateField()),
                ('addevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.addevent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.customer')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
