# Generated by Django 4.0.2 on 2022-04-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmanager',
            name='eventmanager_status',
            field=models.IntegerField(default=0),
        ),
    ]
