# Generated by Django 4.0.2 on 2022-04-29 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0009_eventmanager_eventmanager_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='addevent',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='eventapp.addevent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='description',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
    ]
