# Generated by Django 4.0.2 on 2022-04-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0010_remove_review_review_review_addevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='titel',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
