# Generated by Django 4.0.2 on 2022-04-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0011_review_titel'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
