# Generated by Django 4.0.2 on 2022-05-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0012_review_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='titel',
            new_name='title',
        ),
    ]
