# Generated by Django 4.0.2 on 2022-05-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0014_rename_venueaddress_addevent_venueaddres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addevent',
            old_name='venueaddres',
            new_name='venueaddress',
        ),
    ]
