# Generated by Django 4.0.2 on 2022-05-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0015_rename_venueaddres_addevent_venueaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fullname',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
