# Generated by Django 4.0.2 on 2022-05-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0017_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmanager',
            name='eventmanager_status',
        ),
    ]
