# Generated by Django 4.0.2 on 2022-05-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0018_remove_eventmanager_eventmanager_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Website', models.CharField(max_length=100)),
                ('Message', models.TextField()),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
