# Generated by Django 4.0.2 on 2022-05-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0019_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
